# the lazy version
#FROM nginx:alpine
#COPY . /usr/share/nginx/html

# Multi-stage build example
FROM node:14

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

FROM nginx:1.29-alpine
COPY --from=build /out /usr/share/nginx/html

##################################
# Stage 1 - Build the application
FROM node:14-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2 - Create the production image
FROM nginx:latest
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"



